### ISSUE TITLE
Firmware not flashing on device

### ISSUE THREAD

**Issue by Lalitj03** [cesanta/mongoose-os-smart-light#1]
Hi,
I am not sure it's an issue but didn't know how to resolve this. I am trying to flash my device(NodeMCU) but its opening bluetooth port by default. How can I change this?
```
~/.mos/bin/mos flash
Loaded smartlight/esp8266 version 1.0 (20180918-235327)
Using port /dev/cu.BoseColorIISoundLink-SP
Opening /dev/cu.BoseColorIISoundLink-SP @ 115200...
Error: Failed to talk to bootloader. See https://mongoose-os.com/docs/quickstart/setup.mdfor wiring instructions or put the device into flashing mode manually by pulling GPIO0 low and resetting.: failed to open control port: open /dev/cu.BoseColorIISoundLink-SP: resource busy
```

**Comment by cpq** [comment]
That is most probably a USB-to-Serial driver problem.
Did you check out https://mongoose-os.com/docs/quickstart/setup.md#usb-to-serial-drivers ?

**Comment by Lalitj03** [comment]
Thanks. I was just checking the docs.I will try to setup the port manually.

**Comment by Lalitj03** [comment]
Worked by setting up the port manually.
